## Sensitivity_parameter_sets.R
# 
#========================================================	
# ---
### title: Design sensitivity analysis parameter sets
# author: Marie Gilbertson
# date: "10/09/2020"
#---
###  Preamble	
# 
# What this code does:
# 1. Sensitivity analysis parameter set design for FeLV management simulations


##### Clear Environment #####
remove(list=ls())

#### load libraries ####
library(lhs)
library(extraDistr) # for uniform discrete distribution
library(AlgDesign)

#### set seed ####
set.seed(89422)


#### SENSITIVITY ANALYSES ####

#### no intervention ####
# Parameter distributions divided into N equal probability intervals (N = sample size)
# Marino et al 2009: "The choice for N should be at least k+1, where k is the number of parameters varied,
# but usually much larger to ensure accuracy."


# parameters to vary (k)
# 1. probability of transmission 
# 2. duration of infection (for progressive infections)
# 3. modifier for duration of infection for regressive infections
# 4. modifier for probability of transmission from regressive individuals
# 5. contact rate
# 6. proportion adults
# 7. re-spawn rate
# 8. network density



# LHS tutorial: https://cran.r-project.org/web/packages/lhs/vignettes/lhs_basics.html
# basic design with 150 samples from 11 parameters
A <- randomLHS(50, 8)

# now transform the margins of the design (the columns) into other distributions 

B <- matrix(nrow = nrow(A), ncol = ncol(A))
# 1. probability of transmission (beta-ish)
# range: 9/52 - 15/52, uniform continuous distribution
B[,1] <- qunif(A[,1], min = 9/52, max = 15/52)

# 2. duration of infection (for progressive infections)
# two different means (short, long)
# uniform discrete distribution to draw from these two options (1 = short, 2 = long)
B[,2] <- qdunif(A[,2], min = 1, max = 2)

# 3. modifier for duration of infection for regressive infections
# two different modifiers (0.5 and 1)
# uniform discrete distribution to draw from these two modifiers (1 = 0.5 (shorter), 2 = 1 (same))
B[,3] <- qdunif(A[,3], min = 1, max = 2)

# 4. modifier for probability of transmission from regressive individuals
# three different modifiers (0, 0.1, 0.5)
# uniform discrete distribution to draw from these three modifiers (1 = 0, 2 = 0.1, 3 = 0.5)
B[,4] <- qdunif(A[,4], min = 1, max = 3)


# 5. contact rate
# range: 0.1 - 0.4, uniforrm continuous
B[,5] <- qunif(A[,5], min = 0.1, max = 0.4)


# 6. proportion adults
# rather than having two separate LHS parameters, examine range of values generated by
# two sets of normal distributions based on data from Desert Puma
adults <- rnorm(1000, mean = 0.61, sd = 0.09)
juves <- rnorm(1000, mean = 0.06, sd = 0.02)
props <- adults/(juves+adults)
mean.prop <- mean(props)
sd.prop <- sd(props)
# Now LHS will be transformed to normal distribution, with mean = mean.prop and sd = sd.prop
B[,6] <- qnorm(A[,6], mean = mean.prop, sd = sd.prop)
# some may be just over 1 (can't have a proportion over one), so adjust these to be just under 1
which(B[,6]>=1)
max(subset(B[,6], B[,6]<1))
B[,6][B[,6]>=1] <- 0.99
any(B[,6]>=1)
hist(B[,6])


# 7. re-spawn rate
# range: 1/12 - 1/4; uniform continuous distribution
B[,7] <- qunif(A[,7], min = 1/12, max = 1/4)


# 8. network density
# range: 0.05 - 0.15; univorm continuous distribution
B[,8] <- qunif(A[,8], min = 0.05, max = 0.15)




# evaluate correlation matrix scatterplots
pairs(A)
pairs(B)


# name columns by parameter
colnames(B) <- c("beta",
                 "progr.dur",
                 "regr.dur.c",
                 "c.beta",
                 "c.rate",
                 "a_prop",
                 "terr.repop",
                 "net.den"
)


# convert to dataframe
B.frame <- data.frame(B)



# add parameter set id #
B.frame$set.id <- seq(1:nrow(B.frame))
B.frame <- B.frame[,c(9,1:8)]

# add non-varying parameters 
B.frame$pop.size <- 150
B.frame$prop.outcomes_p <- B.frame$prop.outcomes_r <- 0.25
B.frame$prop.outcomes_a <- 0.5


# convert discrete variables to actual simulation parameter value
# duration of infection (for progressive infections): 1 = 1/18; 2 = 1/26
B.frame$progr.dur <- ifelse(B.frame$progr.dur==1, 1/18, 1/26)

# regr.dur.c: 1 = 0.5 (shorter); 2 = 1 (same)
B.frame$regr.dur.c <- ifelse(B.frame$regr.dur.c==1, 0.5, 1)

# c.beta: 1 = 0, 2 = 0.1, 3 = 0.5
B.frame$c.beta <- ifelse(B.frame$c.beta==1, 0, 
                         ifelse(B.frame$c.beta==2, 0.1, 0.5)
)


# Save no intervention sensitivity parameter sets
# save(B.frame, file = "Parameter_sets/nointer_sensitivity1_params.Rdata")




#### proactive vaccination: Sensitivity 1 ####

### proportion vaccinated at onset ###
prop.pro.vax <- seq(0.2, 0.6, by = 0.2)


### ratio of unboosted to boosted ###
vax.ratio <- c(1, 0, 0.5) # all unboosted, all boosted, 50/50 boosted


### vaccine efficacy (unboosted, boosted) ###
unboost.ve <- 0.4
boost.ve <- 0.8


### generate factorial design for proactive vaccination simulations ###
fact.provax.1 <- gen.factorial(levels = c(
  length(prop.pro.vax),
  length(vax.ratio)
), 
nVars = 2, center = F, 
varNames = c("prop.pro.vax", "vax.ratio"))

fact.provax.2 <- data.frame(prop.pro.vax = prop.pro.vax[fact.provax.1$prop.pro.vax],
                            vax.ratio = vax.ratio[fact.provax.1$vax.ratio]
)


fact.provax.2$unboost.ve <- unboost.ve
fact.provax.2$boost.ve <- boost.ve


### load sample of parameter sets to evaluate with proactive vax variations ###
# (can't run all sensitivity analyses across all proactive vax; using quantile-based sample of parameter sets randomly selected from 
# sensitivity analysis with no interventions)
net_trans_sample <- c("49", "38", "19", "31", "33", "50", "11", "24", "27", "17", "47", "5") # sample of no intervention scenarios selected by quantiles (see manuscript for details)
net_trans <- B.frame[B.frame$set.id %in% net_trans_sample,]
net_trans <- net_trans[order(match(net_trans$set.id, net_trans_sample)),]

net_trans <- net_trans[rep(seq_len(nrow(net_trans)), each = nrow(fact.provax.2)),]
pro.vax_sens <- fact.provax.2[rep(seq_len(nrow(fact.provax.2)), length(net_trans_sample)),]
pro.vax.sens.params <- cbind(pro.vax_sens, net_trans)
pro.vax.sens.params$no.inter.sens1_param.set <- paste0("nointer_sensitivity1_paramset", pro.vax.sens.params$set.id)
pro.vax.sens.params$param.set <- seq(1, nrow(pro.vax.sens.params))

# Save proactive vaccination sensitivity parameter sets
# save(pro.vax.sens.params, file = "Parameter_sets/proactivevax_sensitivity1_params.Rdata")



#### Sensitivity 2 ####
#### baseline ####
# based on plotting "success" against parameter values
a_prop <- c(0.8875, 0.8875, 0.9125, 0.9125)
net.den <- c(0.0875, 0.1125, 0.0875, 0.1125)

# "nointer.baseline" from main simulation parameter set design
nointer.baseline <- get(load(file = "Parameter_sets/nointer_baseline_params.Rdata"))
net_trans_baseline <- nointer.baseline[rep(seq_len(nrow(nointer.baseline)), length(a_prop)),]
net_trans_baseline$a_prop <- a_prop
net_trans_baseline$net.den <- net.den

net_trans_baseline$set.id <- seq(1, nrow(net_trans_baseline))

# save(net_trans_baseline, file = "Parameter_sets/nointer_sensitivity2_params.Rdata")



#### proactive vaccination ####

### proportion vaccinated at onset ###
prop.pro.vax <- seq(0.2, 0.6, by = 0.2)


### ratio of unboosted to boosted ###
vax.ratio <- c(1, 0, 0.5) # all unboosted, all boosted, 50/50 boosted


### vaccine efficacy (unboosted, boosted) ###
unboost.ve <- 0.4
boost.ve <- 0.8


### generate factorial design for proactive vaccination simulations ###
fact.provax.1 <- gen.factorial(levels = c(
  length(prop.pro.vax),
  length(vax.ratio)
), 
nVars = 2, center = F, 
varNames = c("prop.pro.vax", "vax.ratio"))

fact.provax.2 <- data.frame(prop.pro.vax = prop.pro.vax[fact.provax.1$prop.pro.vax],
                            vax.ratio = vax.ratio[fact.provax.1$vax.ratio]
)


fact.provax.2$unboost.ve <- unboost.ve
fact.provax.2$boost.ve <- boost.ve


### load sample of parameter sets to evaluate with proactive vax variations ###
# (can't run all sensitivity analyses across all proactive vax; using quantile-based sample of parameter sets randomly selected from 
# sensitivity analysis with no interventions)
net_trans <- net_trans_baseline[rep(seq_len(nrow(net_trans_baseline)), each = nrow(fact.provax.2)),]
pro.vax_sens <- fact.provax.2[rep(seq_len(nrow(fact.provax.2)), nrow(net_trans_baseline)),]

pro.vax.sens.params <- cbind(pro.vax_sens, net_trans)
names(pro.vax.sens.params)[names(pro.vax.sens.params)=="set.id"] <- "no.inter.sens2_param.set"
pro.vax.sens.params$param.set <- seq(1, nrow(pro.vax.sens.params))

# Save proactive vaccination sensitivity parameter sets
# save(pro.vax.sens.params, file = "Parameter_sets/proactivevax_sensitivity2_params.Rdata")







#### Sensitivity 3 ####
#### baseline ####

# "nointer.baseline" from main simulation parameter set design
nointer.baseline <- get(load(file = "Parameter_sets/nointer_baseline_params.Rdata"))
nointer.baseline <- nointer.baseline[,c("a_prop", "net.den")]

# swap out a_prop and net.den values in sensitivity 1 (for those parameter sets that showed qualitative differences from main results)
sens1.params <- get(load("Parameter_sets/proactivevax_sensitivity1_params.Rdata"))
sens1.params <- sens1.params[!duplicated(sens1.params$beta),]

different <- c(38, 19, 31, 33, 11, 47, 5)
different <- paste("nointer_sensitivity1_paramset", different, sep = "")

sens1.params <- sens1.params[sens1.params$no.inter.sens1_param.set %in% different,]


sens1.params$a_prop <- nointer.baseline$a_prop
sens1.params$net.den <- nointer.baseline$net.den

nointer_sens3_params <- sens1.params[,c(5:18)]
nointer_sens3_params$set.id <- seq(1, nrow(nointer_sens3_params))

# save(nointer_sens3_params, file = "Parameter_sets/nointer_sensitivity3_params.Rdata")



#### proactive vaccination ####

### proportion vaccinated at onset ###
prop.pro.vax <- seq(0.2, 0.6, by = 0.2)


### ratio of unboosted to boosted ###
# NOTE: NOT DOING ALL UNBOOSTED FOR NOW (these are all pretty computationally time-intensive)
vax.ratio <- c(0, 0.5) # all boosted, 50/50 boosted


### vaccine efficacy (unboosted, boosted) ###
unboost.ve <- 0.4
boost.ve <- 0.8


### generate factorial design for proactive vaccination simulations ###
fact.provax.1 <- gen.factorial(levels = c(
  length(prop.pro.vax),
  length(vax.ratio)
), 
nVars = 2, center = F, 
varNames = c("prop.pro.vax", "vax.ratio"))

fact.provax.2 <- data.frame(prop.pro.vax = prop.pro.vax[fact.provax.1$prop.pro.vax],
                            vax.ratio = vax.ratio[fact.provax.1$vax.ratio]
)


fact.provax.2$unboost.ve <- unboost.ve
fact.provax.2$boost.ve <- boost.ve


### load sample of parameter sets to evaluate with proactive vax variations ###
# (can't run all sensitivity analyses across all proactive vax; using quantile-based sample of parameter sets randomly selected from 
# sensitivity analysis with no interventions)
net_trans <- nointer_sens3_params[rep(seq_len(nrow(nointer_sens3_params)), each = nrow(fact.provax.2)),]
pro.vax_sens <- fact.provax.2[rep(seq_len(nrow(fact.provax.2)), nrow(nointer_sens3_params)),]

pro.vax.sens.params <- cbind(pro.vax_sens, net_trans)
names(pro.vax.sens.params)[names(pro.vax.sens.params)=="set.id"] <- "no.inter.sens3_param.set"
pro.vax.sens.params$param.set <- seq(1, nrow(pro.vax.sens.params))

# Save proactive vaccination sensitivity parameter sets
# save(pro.vax.sens.params, file = "Parameter_sets/proactivevax_sensitivity3_params.Rdata")
